= SBuild Adept Plugin

This SBuild plugin integrates http://jbake.org[JBake] with http://sbuild.tototec.de[SBuild].

== Installation

There is currently no release of this plugin. You need to build it by yourself.

== Building from Source

You need a recent version of SBuild.

----
git clone https://github.com/SBuild-org/jbake.git
cd sbuild-sbuild-plugin/org.sbuild.plugins.jbake
sbuild all
----

You will find the built jar in the directory `org.sbuild.plugins.jbake/target`.

== Configuration

All configurable properties are documented via ScalaDoc. See file link:org.sbuild.plugins.jbake/src/main/scala/org/sbuild/plugin/jbake/JBake.scala[`JBake.scala`].

== Example

Minimal example, which will generate a jbake site from `src/jbake` to `target/jbake`.

[source,scala]
----
import de.tototec.sbuild._

// Please note, SBuild 0.7.0 is not sufficient to use this plugin
@version("0.7.0.9000")
@classpath("org.sbuild.plugins.jbake.jar")
class SBuild(implicit _project: Project) {

  import org.sbuild.plugins.jbake._
  Plugin[JBake]

}

