= SBuild Adept Plugin

This SBuild plugin integrates http://jbake.org[JBake] with http://sbuild.tototec.de[SBuild].

== Download

SBuild JBake Plugin can be downloaded from http://repo1.maven.org/maven2/org/sbuild/org.sbuild.plugins.jbake/[Maven Central].

To include it in you SBuild buildfile use the `@classpath` annotation:

[source,scala]
----
@classpath("mvn:org.sbuild:org.sbuild.plugin.jbake:0.1.0")
----

== Building from Source

You need a recent version of SBuild.

----
git clone https://github.com/SBuild-org/jbake.git
cd sbuild-sbuild-plugin/org.sbuild.plugins.jbake
sbuild all
----

You will find the built jar in the directory `org.sbuild.plugins.jbake/target`.

== Requirements

This plugin requires at least SBuild 0.7.1.9000.

== Configuration

All configurable properties are documented via ScalaDoc. See file link:org.sbuild.plugins.jbake/src/main/scala/org/sbuild/plugins/jbake/JBake.scala[`JBake.scala`].

== Examples

Minimal example, which will generate a jbake site from `src/jbake` to `target/jbake`.

[source,scala]
----
import de.tototec.sbuild._

@version("0.7.1.9000")
@classpath("mvn:org.sbuild:org.sbuild.plugins.jbake:0.1.0")
class SBuild(implicit _project: Project) {

  import org.sbuild.plugins.jbake._
  Plugin[JBake]

}
----

Another example, using JBake 2.2.1 to generate a site from `src/website` to `target`.

[source,scala]
----
import de.tototec.sbuild._

@version("0.7.1.9000")
@classpath("mvn:org.sbuild:org.sbuild.plugins.jbake:0.1.0")
class SBuild(implicit _project: Project) {

  import org.sbuild.plugins.jbake._
  Plugin[JBake] configure { _.copy(
    jbakeVersion = JBakeVersion.JBake_2_2_1,
    sourceDir = Path("src/website"),
    targetDir = Path("target")
  )}

}
----

== Changelog

=== SBuild JBake Plugin 0.1.0 - 2014-01-24

* Initial Release, compatible to SBuild 0.7.1.9000 (unreleased)
